export const BUY_CAKE = 'BUY_CAKE'
export const ADD_CAKE = 'ADD_CAKE'
export const ADD_CAKE_SUCCESS_ASYNC = 'ADD_CAKE_SUCCESS_ASYNC'
export const ADD_CAKE_FAILURE_ASYNC = 'ADD_CAKE_FAILURE_ASYNC'

export const BUY_ICECREAM = 'BUY_ICECREAM'
export const ADD_ICECREAM = 'ADD_ICECREAM'
export const ADD_ICECREAM_SUCCESS_ASYNC = 'ADD_ICECREAM_SUCCESS_ASYNC'
export const ADD_ICECREAM_FAILURE_ASYNC = 'ADD_ICECREAM_FAILURE_ASYNC'